### PR TITLE
REFACTOR: Removing inefficient use of `cat`

### PR DESCRIPTION
**Pull request by DLopezJr**
Just removing cat whenever it's not necessary (usually in a pipeline).

Please check this out and ensure that it works on your end and matches. 

Also can you give me rights to the repo? At least the refactor branch, since that will make working on this project  a lot easier for me. Here is a link on how to do that: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-teams-and-people-with-access-to-your-repository#inviting-a-team-or-person

### CODE REVIEW

**Comment by ivan-hc** [comment]
AHAHAH, I'm sorry... I was confusing because I've seen in this PR you have changed 198 files, not just APP-MANAGER

**Comment by DLopezJr** [comment]
Haha no worries. That actually why I'm requesting access to the repo, since it's tough to keep up with your rapid development speed in a fork.

**Comment by DLopezJr** [comment]
Do you have test scripts? If not, we should probably consider that for the refactor as well.

**Comment by ivan-hc** [comment]
Steps to reproduce:

1. Open /opt/any-appimage-you-installed directory with your file manager;
2. open a terminal and write `am --launcher`, then drag/drop the appimage into the terminal and press enter.

With your changes I get errors and the launcher is not created in ~/.local/share/applications/AppImages

**Comment by ivan-hc** [comment]
However, that option I wrote is strongly based on how any other installation script for Appimage packages is wrote. It extracts (or tries to extract) only icons and launchers from the Appimage.

**Pull request merged**
